# R Language Guide — Part 1: Basics & Descriptive Statistics

This notebook covers:
1. **R Basics** — variables, data types, vectors, matrices, data frames, lists, functions, packages
2. **Loading & Exploring Data** — reading CSV files, inspecting structure
3. **Frequency Distributions** — absolute/relative frequencies, class intervals, cumulative frequencies
4. **Position Indexes** — min, max, median, quartiles, percentiles
5. **Averages** — arithmetic mean, weighted mean, geometric mean, harmonic mean

---
## 1. R BASICS

### 1.1 Variables & Assignment

In R, variables are assigned using `<-` (preferred) or `=`.  
Use `print()` to display values.

In [1]:
# Assigning variables
a <- 5
b <- "Hello, World!"
c = 56          # = also works, but <- is conventional

print(a)
print(b)
print(c)

[1] 5
[1] "Hello, World!"
[1] 56

### 1.2 Data Types

R has several basic data types: `numeric`, `character`, `logical`.  
Use `typeof()` to check the type of an object.

In [2]:
# Basic data types
print(typeof(5))          # numeric (double)
print(typeof("ciao"))    # character
print(typeof(TRUE))       # logical
print(typeof(5L))         # integer (L suffix)

[1] "double"
[1] "character"
[1] "logical"
[1] "integer"

In [3]:
# Logical comparisons
print(TRUE)
print(FALSE)
print(5 == 7)   # FALSE
print(5 > 3)    # TRUE

[1] TRUE
[1] FALSE
[1] FALSE
[1] TRUE

### 1.3 Vectors

Vectors are 1D arrays where **all elements must have the same type**.  
Create them with `c()` (combine/concatenate).  
Operations are **element-wise**.

In [4]:
# Creating vectors
x <- c(1, 2, 3, 4, 5)
y <- c(5, 10, 4, 8, 2)

print(x)
print(y)

[1] 1 2 3 4 5
[1]  5 10  4  8  2

In [5]:
# Element-wise operations
x * y          # (1*5, 2*10, 3*4, 4*8, 5*2)
5 + x          # scalar broadcast: (6,7,8,9,10)

[1]  5 20 12 32 10

[1]  6  7  8  9 10

In [6]:
# Concatenating vectors
z <- c(x, y)
print(z)       # just a longer vector, NOT a matrix

 [1]  1  2  3  4  5  5 10  4  8  2

In [8]:
z1 <- c(x, y, 100)  # adding a single value to the vector
z1

 [1]   1   2   3   4   5   5  10   4   8   2 100

### 1.4 Type Coercion

If you mix types in a vector, R automatically **coerces** them to a common type:  
`logical` → `numeric` → `character`

In [10]:
# Type coercion: all become character
m <- c(1, "hello", TRUE)
print(m)
print(typeof(m))   # character

[1] "1"     "hello" "TRUE"
[1] "character"

### 1.5 Sequences

Use `seq()` to generate sequences (like Python's `range()`).

In [11]:
# Sequences
seq(1, 10, by = 2)   # 1 3 5 7 9
1:10                  # shorthand: 1 2 3 ... 10

[1] 1 3 5 7 9

 [1]  1  2  3  4  5  6  7  8  9 10

### 1.6 Matrices

Matrices are 2D arrays. All elements must have the same type.  
R fills **by column** by default.

In [12]:
# Creating a matrix
M <- matrix(1:6, nrow = 2, ncol = 3)
print(M)
# Layout:
# 1 3 5
# 2 4 6

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

In [14]:
c_v = matrix(1:6, nrow=6, ncol= 1)
c_v

     [,1]
[1,] 1
[2,] 2
[3,] 3
[4,] 4
[5,] 5
[6,] 6

### 1.7 Data Frames

A **data frame** is a table where:
- rows = observations
- columns = variables (can have different types)

Internally, it's a **list of column vectors**.

In [15]:
# Creating a data frame
e <- data.frame(
  name = c("Alice", "Bob", "Charlie"),
  age = c(25, 30, 35),
  is_student = c(TRUE, FALSE, TRUE)
)

print(e)
print(typeof(e))   # list

     name age is_student
1   Alice  25       TRUE
2     Bob  30      FALSE
3 Charlie  35       TRUE
[1] "list"

### 1.8 Accessing Elements

Different ways to access elements in R:

In [16]:
# Vector access
x[1]           # first element of x

# Data frame access
e[,1]          # first column as vector
e[1]           # first column as data frame
e[1,1]         # element at row 1, column 1
e["name"]     # column by name (returns data frame)
e$name         # column by name (returns vector)

[1] 1

[1] "Alice"   "Bob"     "Charlie"

  name
1 Alice
2 Bob
3 Charlie

[1] "Alice"

  name
1 Alice
2 Bob
3 Charlie

[1] "Alice"   "Bob"     "Charlie"

### 1.9 Lists

Lists are the most flexible container — they can hold objects of **any type**, including other lists.

In [17]:
# Creating a list
lista <- list(x, y, e, M)
print(lista)

# Access list elements with [[ ]]
lista[[1]]     # first element (vector x)

[[1]]
[1] 1 2 3 4 5

[[2]]
[1]  5 10  4  8  2

[[3]]
     name age is_student
1   Alice  25       TRUE
2     Bob  30      FALSE
3 Charlie  35       TRUE

[[4]]
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

[1] 1 2 3 4 5

### 1.10 Functions

Functions are first-class objects in R. They can be assigned to variables and passed as arguments.

In [18]:
# Defining a function
my_function <- function(x) {
  return(x^2)
}

my_function(5)   # 25

[1] 25

### 1.11 Packages

R can be extended with external packages.  
Install once with `install.packages()`, then load with `library()`.

In [19]:
# Install (run once)
# install.packages("ggplot2")

# Load in current session
library(ggplot2)

### 1.12 Help System

Use `?functionname` or `help(functionname)` to open documentation.

In [20]:
# Open documentation
# ?list
# help(list)

---
## 2. LOADING & EXPLORING DATA

### 2.1 Reading a CSV File

Use `read.csv()` to load data.  
The `sep` parameter specifies the delimiter (e.g., `";"` for semicolons).

In [5]:
# Load the tonni (tuna) dataset
dati <- read.csv("tonni.csv", sep = ";")

# Print the entire dataset
print(dati)

   ID            LOCALITa SESSO LUNGHEZZA PESO
1   1           CAPOGALLO     F        15  180
2   2           CAPOGALLO     M        30  299
3   3           CAPOGALLO     F        22  240
4   4           CAPOGALLO     M        20  220
5   5           CAPOGALLO     F        17  171
6   6           CAPOGALLO     M        20  240
7   7           CAPOGALLO     F        17  180
8   8              CARINI     F        21  230
9   9              CARINI     M        15  100
10 10              CARINI     M        11   87
11 11              CARINI     F        12   78
12 12 ISOLA DELLE FEMMINE     M        16   25
13 13 ISOLA DELLE FEMMINE     M        20  241
14 14 ISOLA DELLE FEMMINE     M        16  205
15 15 ISOLA DELLE FEMMINE     F        21  222
16 16 ISOLA DELLE FEMMINE     F        12   90
17 17 ISOLA DELLE FEMMINE     M        11  110
18 18 ISOLA DELLE FEMMINE     F        19  201
19 19 ISOLA DELLE FEMMINE     F        24  250
20 20 ISOLA DELLE FEMMINE     F        12  100

In [6]:
typeof(dati)
# a nemed list actually
dati$ID

[1] "list"

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

### 2.2 Exploring the Dataset

Key functions to inspect a dataset:

In [7]:
# Structure: variable names, types, preview
str(dati)

# Dimensions: [rows, columns]
dim(dati)

# Summary statistics
summary(dati)

'data.frame':	20 obs. of  5 variables:
 $ ID       : int  1 2 3 4 5 6 7 8 9 10 ...
 $ LOCALITa : chr  "CAPOGALLO" "CAPOGALLO" "CAPOGALLO" "CAPOGALLO" ...
 $ SESSO    : chr  "F" "M" "F" "M" ...
 $ LUNGHEZZA: int  15 30 22 20 17 20 17 21 15 11 ...
 $ PESO     : int  180 299 240 220 171 240 180 230 100 87 ...

[1] 20  5

       ID          LOCALITa            SESSO             LUNGHEZZA
 Min.   : 1.00   Length:20          Length:20          Min.   :11.00
 1st Qu.: 5.75   Class :character   Class :character   1st Qu.:14.25
 Median :10.50   Mode  :character   Mode  :character   Median :17.00
 Mean   :10.50                                         Mean   :17.55
 3rd Qu.:15.25                                         3rd Qu.:20.25
 Max.   :20.00                                         Max.   :30.00
      PESO
 Min.   : 25.0
 1st Qu.:100.0
 Median :190.5
 Mean   :173.4
 3rd Qu.:232.5
 Max.   :299.0

In [8]:
# Number of observations (population size)
N <- dim(dati)[1]
print(N)

[1] 20

---
## 3. FREQUENCY DISTRIBUTIONS

### 3.1 Qualitative Variables

`table()` counts occurrences of each category.

In [ ]:
# Frequency table for SESSO (sex)
table(dati["SESSO"])

# Absolute frequencies
freq_ass <- table(dati$SESSO)
freq_ass
# Relative frequencies (divide by N)
freq_rel <- table(dati$SESSO) / N
freq_rel

# Combine into one table
distr_freq_sex <- cbind(freq_ass, freq_rel)
print(distr_freq_sex)

SESSO
 F  M
11  9

 F  M
11  9

   F    M
0.55 0.45

  freq_ass freq_rel
F       11     0.55
M        9     0.45

In [10]:
#why didn't use c instead of cbind?
distr_freq_sex2 <- c(freq_ass, freq_rel)
print(distr_freq_sex2)

#cause the ouput is different, u cobine the two tables with c(), with cbind instead u create a vector with the two tables, column one will be one table, columntwo the other one.
distr_freq_sex <- cbind(freq_ass, freq_rel)
print(distr_freq_sex)

    F     M     F     M
11.00  9.00  0.55  0.45
  freq_ass freq_rel
F       11     0.55
M        9     0.45

In [13]:
#if u wann bind through rows instead u use rbind.
distr_sex_rbind <- rbind(freq_ass, freq_rel)
distr_sex_rbind

         F     M
freq_ass 11.00 9.00
freq_rel  0.55 0.45

In [1]:
?cbind

cbind                   package:base                   R Documentation

_C_o_m_b_i_n_e _R _O_b_j_e_c_t_s _b_y _R_o_w_s _o_r _C_o_l_u_m_n_s

_D_e_s_c_r_i_p_t_i_o_n:

     Take a sequence of vector, matrix or data-frame arguments and
     combine by _c_olumns or _r_ows, respectively.  These are generic
     functions with methods for other R classes.

_U_s_a_g_e:

     cbind(..., deparse.level = 1)
     rbind(..., deparse.level = 1)
     ## S3 method for class 'data.frame'
     rbind(..., deparse.level = 1, make.row.names = TRUE,
           stringsAsFactors = FALSE, factor.exclude = TRUE)

_A_r_g_u_m_e_n_t_s:

     ...: (generalized) vectors or matrices.  These can be given as
          named arguments.  Other R objects may be coerced as
          appropriate, or S4 methods may be used: see sections
          ‘Details’ and ‘Value’.  (For the ‘"data.frame"’ method of
          ‘cbind’ these can be further arguments to ‘data.frame’ such
          as ‘stringsAsFactors’.)

deparse.level: integer controlling the construction of labels in the
          case of non-matrix-like arguments (for the default method):
          ‘deparse.level = 0’ constructs no labels;
          the default ‘deparse.level = 1’ typically and ‘deparse.level
          = 2’ always construct labels from the argument names, see the
          ‘Value’ section below.

make.row.names: (only for data frame method:) logical indicating if
          unique and valid ‘row.names’ should be constructed from the
          arguments.

stringsAsFactors: logical, passed to ‘as.data.frame’; only has an
          effect when the ‘...’ arguments contain a (non-‘data.frame’)
          ‘character’.

factor.exclude: if the data frames contain factors, the default ‘TRUE’
          ensures that ‘NA’ levels of factors are kept, see PR#17562
          and the ‘Data frame methods’.  In R versions up to 3.6.x,
          ‘factor.exclude = NA’ has been implicitly hardcoded (R <=
          3.6.0) or the default (R = 3.6.x, x >= 1).

_D_e_t_a_i_l_s:

     The functions ‘cbind’ and ‘rbind’ are S3 generic, with methods for
     data frames.  The data frame method will be used if at least one
     argument is a data frame and the rest are vectors or matrices.
     There can be other methods; in particular, there is one for time
     series objects.  See the section on ‘Dispatch’ for how the method
     to be used is selected.  If some of the arguments are of an S4
     class, i.e., ‘isS4(.)’ is true, S4 methods are sought also, and
     the hidden ‘cbind’ / ‘rbind’ functions from package ‘methods’
     maybe called, which in turn build on ‘cbind2’ or ‘rbind2’,
     respectively.  In that case, ‘deparse.level’ is obeyed, similarly
     to the default method.

     In the default method, all the vectors/matrices must be atomic
     (see ‘vector’) or lists.  Expressions are not allowed.  Language
     objects (such as formulae and calls) and pairlists will be coerced
     to lists: other objects (such as names and external pointers) will
     be included as elements in a list result.  Any classes the inputs
     might have are discarded (in particular, factors are replaced by
     their internal codes).

     If there are several matrix arguments, they must all have the same
     number of columns (or rows) and this will be the number of columns
     (or rows) of the result.  If all the arguments are vectors, the
     number of columns (rows) in the result is equal to the length of
     the longest vector.  Values in shorter arguments are recycled to
     achieve this length (with a ‘warning’ if they are recycled only
     _fractionally_).

     When the arguments consist of a mix of matrices and vectors the
     number of columns (rows) of the result is determined by the number
     of columns (rows) of the matrix arguments.  Any vectors have their
     values recycled or subsetted to achieve this length.

     For ‘cbind’ (‘rbind’), vectors of zero length (including ‘NULL’)
     are ignored unless the result would have zero rows (columns), for
     S compatibility.  (Zero-extent matrices do not occur in S3 and are
     not ignored in R.)

     Matrices are restricted to less than 2^31 rows and columns even on
     64-bit systems.  So input vectors have the same length
     restriction: as from R 3.2.0 input matrices with more elements
     (but meeting the row and column restrictions) are allowed.

_V_a_l_u_e:

     For the default method, a matrix combining the ‘...’ arguments
     column-wise or row-wise.  (Exception: if there are no inputs or
     all the inputs are ‘NULL’, the value is ‘NULL’.)

     The type of a matrix result determined from the highest type of
     any of the inputs in the hierarchy raw < logical < integer <
     double < complex < character < list .

     For ‘cbind’ (‘rbind’) the column (row) names are taken from the
     ‘colnames’ (‘rownames’) of the arguments if these are matrix-like.
     Otherwise from the names of the arguments or where those are not
     supplied and ‘deparse.level > 0’, by deparsing the expressions
     given, for ‘deparse.level = 1’ only if that gives a sensible name
     (a ‘symbol’, see ‘is.symbol’).

     For ‘cbind’ row names are taken from the first argument with
     appropriate names: rownames for a matrix, or names for a vector of
     length the number of rows of the result.

     For ‘rbind’ column names are taken from the first argument with
     appropriate names: colnames for a matrix, or names for a vector of
     length the number of columns of the result.

_D_a_t_a _f_r_a_m_e _m_e_t_h_o_d_s:

     The ‘cbind’ data frame method is just a wrapper for
     ‘data.frame(..., check.names = FALSE)’.  This means that it will
     split matrix columns in data frame arguments.

     The ‘rbind’ data frame method first drops all zero-column and
     zero-row arguments.  (If that leaves none, it returns the first
     argument with columns otherwise a zero-column zero-row data
     frame.)  It then takes the classes of the columns from the first
     data frame, and matches columns by name (rather than by position).
     Factors have their levels expanded as necessary (in the order of
     the levels of the level sets of the factors encountered) and the
     result is an ordered factor if and only if all the components were
     ordered factors.  Old-style categories (integer vectors with
     levels) are promoted to factors.

     Note that for result column ‘j’, ‘factor(., exclude = X(j))’ is
     applied, where

       X(j) := if(isTRUE(factor.exclude)) {
                  if(!NA.lev[j]) NA # else NULL
               } else factor.exclude

     where ‘NA.lev[j]’ is true iff any contributing data frame has had
     a ‘factor’ in column ‘j’ with an explicit ‘NA’ level.

_D_i_s_p_a_t_c_h:

     The method dispatching is _not_ done via ‘UseMethod()’, but by
     C-internal dispatching.  Therefore there is no need for, e.g.,
     ‘rbind.default’.

     The dispatch algorithm is described in the source file
     (‘.../src/main/bind.c’) as

       1. For each argument we get the list of possible class
          memberships from the class attribute.

       2. We inspect each class in turn to see if there is an
          applicable method.

       3. If we find a method, we use it.  Otherwise, if there was an
          S4 object among the arguments, we try S4 dispatch; otherwise,
          we use the default code.

     If you want to combine other objects with data frames, it may be
     necessary to coerce them to data frames first.  (Note that this
     algorithm can result in calling the data frame method if all the
     arguments are either data frames or vectors, and this will result
     in the coercion of character vectors to factors.)

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘c’ to combine vectors (and lists) as vectors, ‘data.frame’ to
     combine vectors and matrices as a data frame.

_E_x_a_m_p_l_e_s:

     m <- cbind(1, 1:7) # the '1' (= shorter vector) is recycled
     m
     m <- cbind(m, 8:14)[, c(1, 3, 2)] # insert a column
     m
     cbind(1:7, diag(3)) # vector is subset -> warning

     cbind(0, rbind(1, 1:3))
     cbind(I = 0, X = rbind(a = 1, b = 1:3))  # use some names
     xx <- data.frame(I = rep(0,2))
     cbind(xx, X = rbind(a = 1, b = 1:3))   # named differently

     cbind(0, matrix(1, nrow = 0, ncol = 4)) #> Warning (making sense)
     dim(cbind(0, matrix(1, nrow = 2, ncol = 0))) #-> 2 x 1

     ## deparse.level
     dd <- 10
     rbind(1:4, c = 2, "a++" = 10, dd, deparse.level = 0) # middle 2 rownames
     rbind(1:4, c = 2, "a++" = 10, dd, deparse.level = 1) # 3 rownames (default)
     rbind(1:4, c = 2, "a++" = 10, dd, deparse.level = 2) # 4 rownames

     ## cheap row names:
     b0 <- gl(3,4, labels=letters[1:3])
     bf <- setNames(b0, paste0("o", seq_along(b0)))
     df  <- data.frame(a = 1, B = b0, f = gl(4,3))
     df. <- data.frame(a = 1, B = bf, f = gl(4,3))
     new <- data.frame(a = 8, B ="B", f = "1")
     (df1  <- rbind(df , new))
     (df.1 <- rbind(df., new))
     stopifnot(identical(df1, rbind(df,  new, make.row.names=FALSE)),
               identical(df1, rbind(df., new, make.row.names=FALSE)))

In [14]:
# Frequency distribution for LOCALITA (location)
freq_ass <- table(dati$LOCALITa)
freq_rel <- table(dati$LOCALITa) / N
distr_freq_loc <- cbind(freq_ass, freq_rel)
print(distr_freq_loc)

                    freq_ass freq_rel
CAPOGALLO                  7     0.35
CARINI                     4     0.20
ISOLA DELLE FEMMINE        9     0.45

### 3.2 Creating Classes for a Quantitative Variable

Use `cut()` to divide a numeric variable into class intervals.

In [17]:
summary(dati)

       ID          LOCALITa            SESSO             LUNGHEZZA
 Min.   : 1.00   Length:20          Length:20          Min.   :11.00
 1st Qu.: 5.75   Class :character   Class :character   1st Qu.:14.25
 Median :10.50   Mode  :character   Mode  :character   Median :17.00
 Mean   :10.50                                         Mean   :17.55
 3rd Qu.:15.25                                         3rd Qu.:20.25
 Max.   :20.00                                         Max.   :30.00
      PESO        LUNGHEZZA_CL
 Min.   : 25.0   (10,15]:7
 1st Qu.:100.0   (15,20]:8
 Median :190.5   (20,25]:4
 Mean   :173.4   (25,30]:1
 3rd Qu.:232.5
 Max.   :299.0

In [ ]:
# Check min and max of LUNGHEZZA (length)
print(min(dati$LUNGHEZZA))
print(max(dati$LUNGHEZZA))

# Create classes, NB, u are attacching this new object to the table.
dati$LUNGHEZZA_CL <- cut(
  dati$LUNGHEZZA,
  breaks = c(10, 15, 20, 25, 30)
)

print(dati$LUNGHEZZA_CL)

[1] 11
[1] 30
 [1] (10,15] (25,30] (20,25] (15,20] (15,20] (15,20] (15,20] (20,25] (10,15]
[10] (10,15] (10,15] (15,20] (15,20] (15,20] (20,25] (10,15] (10,15] (15,20]
[19] (20,25] (10,15]
Levels: (10,15] (15,20] (20,25] (25,30]

### 3.3 Frequency Distribution for Classes

Compute absolute frequencies (`ni`), relative frequencies (`fi`),  
cumulative absolute frequencies (`Ni`), and cumulative relative frequencies (`Fi`).

In [18]:
# Absolute frequencies
ni <- table(dati$LUNGHEZZA_CL)

# Relative frequencies
fi <- table(dati$LUNGHEZZA_CL) / N

# Cumulative absolute frequencies
Ni <- cumsum(ni)

# Cumulative relative frequencies
Fi <- Ni / N

print(ni)
print(fi)
print(Ni)

(10,15] (15,20] (20,25] (25,30]
      7       8       4       1

(10,15] (15,20] (20,25] (25,30]
   0.35    0.40    0.20    0.05
(10,15] (15,20] (20,25] (25,30]
      7      15      19      20

In [19]:
# Build final frequency table
distr_freq_lung_cl <- as.data.frame(
  cbind(ni, fi, Ni, Fi)
)

print(distr_freq_lung_cl)

        ni   fi Ni   Fi
(10,15]  7 0.35  7 0.35
(15,20]  8 0.40 15 0.75
(20,25]  4 0.20 19 0.95
(25,30]  1 0.05 20 1.00

In [20]:
# Contingency table (two variables)
print(table(dati$SESSO, dati$LOCALITa))

    CAPOGALLO CARINI ISOLA DELLE FEMMINE
  F         4      2                   5
  M         3      2                   4

### 3.4 Exporting Results to CSV

In [ ]:
# Save frequency table to CSV
write.csv(
  distr_freq_lung_cl,
  file = "distr_freq_lung_cl.csv"
)

---
## 4. POSITION INDEXES

Let's work with the built-in `iris` dataset.

In [21]:
# Load iris dataset
data("iris")
print(head(iris))

# Attach so we can refer to columns by name directly
attach(iris)

# Check species distribution
print(table(Species))   # 50 each → trimodal

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa
Species
    setosa versicolor  virginica
        50         50         50

### 4.1 Min, Max, Range

In [22]:
# Min, max, range
print(min(Petal.Length))
print(max(Petal.Length))
print(range(Petal.Length))   # c(min, max)

[1] 1
[1] 6.9
[1] 1.0 6.9

### 4.2 Median & Quartiles (Manual)

In [23]:
# Manual median calculation
n <- length(Petal.Length)

if (n %% 2 == 0) {
  median_val <- (Petal.Length[n/2] + Petal.Length[n/2 + 1]) / 2
} else {
  median_val <- Petal.Length[as.integer(n/2) + 1]
}
print(median_val)

# Compare with built-in
print(median(Petal.Length))

[1] 4.35
[1] 4.35

### 4.3 Quantiles & Percentiles

Use `quantile()` to get any percentile.  
The median is the 2nd quartile (50th percentile).

In [24]:
# Quartiles
print(quantile(Petal.Length, probs = c(0, 0.25, 0.5, 0.75, 1)))

# Percentiles (deciles)
print(quantile(Petal.Length, probs = seq(0, 1, by = 0.1)))

# Summary gives all key position indexes
print(summary(Petal.Length))

  0%  25%  50%  75% 100%
1.00 1.60 4.35 5.10 6.90
  0%  10%  20%  30%  40%  50%  60%  70%  80%  90% 100%
1.00 1.40 1.50 1.70 3.90 4.35 4.64 5.00 5.32 5.80 6.90
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  1.000   1.600   4.350   3.758   5.100   6.900

### 4.4 Working with Classes

Let's create classes for Petal.Length and compute the frequency distribution.

In [25]:
# Create classes for Petal.Length
Petal.Length_cl <- cut(Petal.Length, seq(0, 7.1))
print(table(Petal.Length_cl))

Petal.Length_cl
(0,1] (1,2] (2,3] (3,4] (4,5] (5,6] (6,7]
    1    49     1    15    42    33     9

In [26]:
# Full frequency table with cumulative frequencies
distr_freq <- as.data.frame(
  cbind(
    ni = table(Petal.Length_cl),
    fi = table(Petal.Length_cl) / length(Petal.Length),
    Ni = cumsum(table(Petal.Length_cl)),
    Fi = cumsum(table(Petal.Length_cl)) / length(Petal.Length)
  )
)
print(distr_freq)

      ni          fi  Ni          Fi
(0,1]  1 0.006666667   1 0.006666667
(1,2] 49 0.326666667  50 0.333333333
(2,3]  1 0.006666667  51 0.340000000
(3,4] 15 0.100000000  66 0.440000000
(4,5] 42 0.280000000 108 0.720000000
(5,6] 33 0.220000000 141 0.940000000
(6,7]  9 0.060000000 150 1.000000000

---
## 5. AVERAGES

### 5.1 Arithmetic Mean

In [27]:
# Arithmetic mean
print(mean(Petal.Length))

# Manual calculation
print(sum(Petal.Length) / n)

[1] 3.758
[1] 3.758

### 5.2 Robustness of Median

The median is **robust** to outliers — the mean is not.

In [28]:
# Add extreme outliers
print(mean(c(Petal.Length, 541, 378)))
print(mean(Petal.Length))   # original mean is much lower

print(median(c(Petal.Length, 541, 378)))
print(median(Petal.Length))  # median barely changes

[1] 9.754605
[1] 3.758
[1] 4.4
[1] 4.35

### 5.3 Weighted Mean (for Class Data)

When data is grouped into classes, we use the **weighted mean**  
with class frequencies (`ni`) as weights and class midpoints (`cxi`) as values.

In [29]:
# Add class midpoints
distr_freq$cxi <- seq(0.5, 6.5, 1)
print(distr_freq)

# Weighted mean manually
sum(distr_freq$cxi * distr_freq$ni) / sum(distr_freq$ni)

# Using built-in function
weighted.mean(distr_freq$cxi, distr_freq$ni)

      ni          fi  Ni          Fi cxi
(0,1]  1 0.006666667   1 0.006666667 0.5
(1,2] 49 0.326666667  50 0.333333333 1.5
(2,3]  1 0.006666667  51 0.340000000 2.5
(3,4] 15 0.100000000  66 0.440000000 3.5
(4,5] 42 0.280000000 108 0.720000000 4.5
(5,6] 33 0.220000000 141 0.940000000 5.5
(6,7]  9 0.060000000 150 1.000000000 6.5

[1] 3.72

[1] 3.72

### 5.4 Geometric Mean

Useful for **percentage changes / growth rates** (e.g., stock returns).  
Not available in base R — we define it manually.

In [30]:
# Example: cell growth data
cells <- c(1000, 2100, 3000, 5000)

# Install quantmod for percentage changes
# install.packages("quantmod")
library(quantmod)

increments <- quantmod::Delt(cells) * 100
print(increments)

Loading required package: xts

Loading required package: zoo


Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric


Loading required package: TTR

Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo

     Delt.1.arithmetic
[1,]                NA
[2,]         110.00000
[3,]          42.85714
[4,]          66.66667

In [31]:
# Remove the first NA value
increments <- increments[-1, 1]
print(increments)

# Define geometric mean function
geom.mean <- function(x) {
  return(prod(x)^(1 / length(x)))
}

# Compare geometric vs arithmetic mean
print(geom.mean(increments))
print(mean(increments))

[1] 110.00000  42.85714  66.66667
[1] 67.98945
[1] 73.1746

### 5.5 Harmonic Mean

Useful for **rates** (e.g., speeds over equal distances).

In [32]:
# Example: speeds over equal distances
speed <- c(100, 80, 40, 90)

# Arithmetic mean (not appropriate for rates)
print(mean(speed))

# Harmonic mean (appropriate for rates)
harmonic.mean <- function(x) {
  return(length(x) / sum(1 / x))
}

print(harmonic.mean(speed))

[1] 77.5
[1] 68.24645

---
## Summary — Part 1

| Concept | Key Functions |
|---------|--------------|
| Variables | `<-`, `print()` |
| Data types | `typeof()`, `numeric`, `character`, `logical` |
| Vectors | `c()`, element-wise operations |
| Matrices | `matrix()` |
| Data frames | `data.frame()`, `$`, `[]` |
| Lists | `list()`, `[[ ]]` |
| Functions | `function() { }` |
| Packages | `install.packages()`, `library()` |
| Load data | `read.csv()` |
| Explore | `str()`, `dim()`, `summary()`, `head()` |
| Frequencies | `table()`, `cut()`, `cumsum()`, `cbind()` |
| Position | `min()`, `max()`, `range()`, `median()`, `quantile()` |
| Averages | `mean()`, `weighted.mean()`, geometric, harmonic |
| Export | `write.csv()` |