In [4]:
# position index

data("iris")    #preloaded data

print(head(iris))

levels(iris$Species)

attach(iris)    #attach the data frame to the search path, so that you can refer to the variables by name
table(Species)


print(table(Species))   #distrib trimodal, all species have the same number of observations (50)

#with species u can only use mode

#let's consider petal lenght

print(min(Petal.Length))
print(max(Petal.Length))
print(mean(Petal.Length))
print(median(Petal.Length))

#manually?

n=length(Petal.Length)

print(sort(Petal.Length)[1])
print(sort(Petal.Length)[n])

#median
print(Petal.Length[as.integer(n/2)])

#or better

if (n %% 2 == 0) {
  median <- (Petal.Length[n/2] + Petal.Length[n/2 + 1]) / 2
} else {
  median <- Petal.Length[as.integer(n/2) + 1]
}
print(median)

#but median == second quartile.

print(Petal.Length[as.integer(n/4)+1])

print(Petal.Length[as.integer(3*n/4)+1])
# not quite right, because the position of the quartiles is not always an integer, so we need to interpolate between the two closest values.

print(quantile(Petal.Length, probs = c(0, 0.25, 0.5, 0.75, 1)))

#but u can also get the percentiles
print(quantile(Petal.Length, probs = seq(0, 1, by = 0.1)))

#let's use the summary function
print(summary(Petal.Length))



#now the averages
print(mean(Petal.Length))
#or
print(sum(Petal.Length)/n)


#here is why median is robust

c(Petal.Length, 541 , 378)
print(mean(c(Petal.Length, 541 , 378)))
print(mean(Petal.Length))

print(median(c(Petal.Length, 541 , 378)))
print(median(Petal.Length))


#another type of avearge?

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa

[1] "setosa"     "versicolor" "virginica"

Species
    setosa versicolor  virginica
        50         50         50

Species
    setosa versicolor  virginica
        50         50         50
[1] 1
[1] 6.9
[1] 3.758
[1] 4.35
[1] 1
[1] 6.9
[1] 4.3
[1] 4.35
[1] 1.4
[1] 5.5
  0%  25%  50%  75% 100%
1.00 1.60 4.35 5.10 6.90
  0%  10%  20%  30%  40%  50%  60%  70%  80%  90% 100%
1.00 1.40 1.50 1.70 3.90 4.35 4.64 5.00 5.32 5.80 6.90
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  1.000   1.600   4.350   3.758   5.100   6.900
[1] 3.758
[1] 3.758

  [1]   1.4   1.4   1.3   1.5   1.4   1.7   1.4   1.5   1.4   1.5   1.5   1.6
 [13]   1.4   1.1   1.2   1.5   1.3   1.4   1.7   1.5   1.7   1.5   1.0   1.7
 [25]   1.9   1.6   1.6   1.5   1.4   1.6   1.6   1.5   1.5   1.4   1.5   1.2
 [37]   1.3   1.4   1.3   1.5   1.3   1.3   1.3   1.6   1.9   1.4   1.6   1.4
 [49]   1.5   1.4   4.7   4.5   4.9   4.0   4.6   4.5   4.7   3.3   4.6   3.9
 [61]   3.5   4.2   4.0   4.7   3.6   4.4   4.5   4.1   4.5   3.9   4.8   4.0
 [73]   4.9   4.7   4.3   4.4   4.8   5.0   4.5   3.5   3.8   3.7   3.9   5.1
 [85]   4.5   4.5   4.7   4.4   4.1   4.0   4.4   4.6   4.0   3.3   4.2   4.2
 [97]   4.2   4.3   3.0   4.1   6.0   5.1   5.9   5.6   5.8   6.6   4.5   6.3
[109]   5.8   6.1   5.1   5.3   5.5   5.0   5.1   5.3   5.5   6.7   6.9   5.0
[121]   5.7   4.9   6.7   4.9   5.7   6.0   4.8   4.9   5.6   5.8   6.1   6.4
[133]   5.6   5.1   5.6   6.1   5.6   5.5   4.8   5.4   5.6   5.1   5.1   5.9
[145]   5.7   5.2   5.0   5.2   5.4   5.1 541.0 378.0

[1] 9.754605
[1] 3.758
[1] 4.4
[1] 4.35

Let's work on classes

In [5]:
Petal.Length_cl = cut(Petal.Length, seq(0, 7.1))

In [6]:
table(Petal.Length_cl)

Petal.Length_cl
(0,1] (1,2] (2,3] (3,4] (4,5] (5,6] (6,7]
    1    49     1    15    42    33     9

In [13]:
ditr_freq = as.data.frame(
    cbind(ni = table(Petal.Length_cl),
        fi = table(Petal.Length_cl)/length(Petal.Length),
        Ni = cumsum(table(Petal.Length_cl)),
        Fi = cumsum(table(Petal.Length_cl))/length(Petal.Length)
    )
)

In [14]:
ditr_freq

      ni fi          Ni  Fi
(0,1]  1 0.006666667   1 0.006666667
(1,2] 49 0.326666667  50 0.333333333
(2,3]  1 0.006666667  51 0.340000000
(3,4] 15 0.100000000  66 0.440000000
(4,5] 42 0.280000000 108 0.720000000
(5,6] 33 0.220000000 141 0.940000000
(6,7]  9 0.060000000 150 1.000000000

So (4,5] is the median class
(5,6] is the third quartile
(1,2] is the first quartile

In [11]:
quantile(Petal.Length)

  0%  25%  50%  75% 100%
1.00 1.60 4.35 5.10 6.90

Average, for classes it's called weighted average

we said that weights are the ni

In [17]:
ditr_freq$cxi = seq(0.5, 6.5, 1)
ditr_freq

      ni fi          Ni  Fi          cxi
(0,1]  1 0.006666667   1 0.006666667 0.5
(1,2] 49 0.326666667  50 0.333333333 1.5
(2,3]  1 0.006666667  51 0.340000000 2.5
(3,4] 15 0.100000000  66 0.440000000 3.5
(4,5] 42 0.280000000 108 0.720000000 4.5
(5,6] 33 0.220000000 141 0.940000000 5.5
(6,7]  9 0.060000000 150 1.000000000 6.5

In [19]:
sum(ditr_freq$cxi * ditr_freq$ni)/sum(ditr_freq$ni)

[1] 3.72

In [20]:
weighted.mean(ditr_freq$cxi, ditr_freq$ni)

[1] 3.72

Other type of avearegs?

In [28]:
cells = c(1000, 2100, 3000, 5000)

In [29]:
# install.packages("quantmod")
increments = quantmod::Delt(cells)*100
increments

     Delt.1.arithmetic
[1,]        NA
[2,] 110.00000
[3,]  42.85714
[4,]  66.66667

These are percentages ... so geometric ave is the right one

In [30]:
increments = increments[-1,1]   #to avoid the first NA value

geom mean does not exist in base package

In [32]:
geom.mean = function(x) {
  return(prod(x)^(1/length(x)))
}

In [33]:
geom.mean(increments)

[1] 67.98945

In [34]:
mean(increments)

[1] 73.1746

Just the armonic

In [35]:
speed = c(100, 80, 40 ,90)
mean(speed)

[1] 77.5

In [ ]:
#but it's better to use the harmonic mean, because we are dealing with speeds, 
# and the harmonic mean is more appropriate for rates.

harmonic.mean = function(x) {
  return(length(x)/sum(1/x))    #this is 1/mean(x)
}

harmonic.mean(speed)

[1] 68.24645